/**
 * The simulated government portal.
 *
 * DEMO IMPLEMENTATION. Every record this returns is generated by this file.
 * It is not a government API, it does not contact one, and no real endpoint is
 * invented. `isMock` is true and the UI is required to say so wherever these
 * results are shown.
 *
 * It is a realistic simulation rather than a stub, for one reason: the product
 * exists to detect disagreement between the government's record and the
 * citizen's experience. A stub that always succeeds could not produce that
 * disagreement, so there would be nothing to demonstrate. This writes to its
 * own `gov_*` tables, which the demo console manipulates directly, so a
 * discrepancy on stage is a genuine disagreement between two stores rather
 * than a hard-coded screen.
 *
 * Deliberately modelled portal behaviours:
 *   - a duplicate application for the same scheme and citizen is rejected,
 *     as a real portal would,
 *   - submission is idempotent on the caller's key,
 *   - every status change appends to an event log, which is the evidence the
 *     root-cause agent later cites,
 *   - a disbursement can be RELEASED and simultaneously have failed to
 *     arrive, which is the entire point.
 */

import { createHash } from "node:crypto";

import { prisma } from "@/lib/db";
import { log } from "@/lib/log";
import type {
  CorrectInformationInput,
  GovApplicationStatusResult,
  GovDisbursementRecord,
  GovGateway,
  GovOperationResult,
  SubmitApplicationInput,
  SubmitApplicationResult,
  SubmitDocumentInput,
} from "./govGateway";
import type { GovApplicationStatus } from "@/lib/generated/prisma/enums";

/**
 * Deterministic reference, so a demo run is reproducible.
 *
 * Hashed rather than truncated. The previous version kept the first fourteen
 * characters of the joined parts, and the ids fed into it are time-ordered,
 * so two records created close together shared a prefix and got the same
 * reference.
 */
function makeRef(prefix: string, parts: string[]): string {
  const digest = createHash("sha256")
    .update(parts.join("|"))
    .digest("hex")
    .slice(0, 10)
    .toUpperCase();
  return `${prefix}${digest}`;
}

async function toStatusResult(
  applicationRef: string,
): Promise<GovApplicationStatusResult | null> {
  const application = await prisma.govApplication.findUnique({
    where: { applicationRef },
  });
  if (!application) return null;

  const events = await prisma.govStatusEvent.findMany({
    where: { applicationRef },
    orderBy: { occurredOn: "asc" },
  });

  return {
    applicationRef: application.applicationRef,
    schemeCode: application.schemeCode,
    status: application.status,
    receivedOn: application.receivedOn,
    decidedOn: application.decidedOn,
    rejectionReason: application.rejectionReason,
    pendingDocument: application.pendingDocument,
    events: events.map((event) => ({
      status: event.status,
      note: event.note,
      occurredOn: event.occurredOn,
    })),
  };
}

/**
 * Validate a submission the way a portal would: presence and format only.
 *
 * Deliberately shallow. A real portal does not re-derive eligibility at
 * submission, and simulating that it does would hide the realistic failure
 * mode this product cares about - an application accepted, then stalled or
 * rejected later for a reason nobody told the citizen.
 */
function validateFields(
  input: SubmitApplicationInput,
): Array<{ field: string; message: string }> {
  const errors: Array<{ field: string; message: string }> = [];

  const aadhaar = input.fields.aadhaarNumber;
  if (typeof aadhaar === "string" && !/^\d{12}$/.test(aadhaar.replace(/\s/g, ""))) {
    errors.push({ field: "aadhaarNumber", message: "Must be 12 digits." });
  }

  const ifsc = input.fields.ifscCode;
  if (typeof ifsc === "string" && !/^[A-Z]{4}0[A-Z0-9]{6}$/.test(ifsc.trim())) {
    errors.push({ field: "ifscCode", message: "Not a valid IFSC code." });
  }

  const account = input.fields.bankAccountNumber;
  if (typeof account === "string" && !/^\d{9,18}$/.test(account.replace(/\s/g, ""))) {
    errors.push({
      field: "bankAccountNumber",
      message: "Must be between 9 and 18 digits.",
    });
  }

  return errors;
}

/**
 * Create the mock gateway.
 *
 * `failureMode` lets the demo console make the portal misbehave on purpose,
 * so error handling can be shown working rather than asserted.
 */
export function createMockGovGateway(options?: {
  failureMode?: "none" | "unavailable";
}): GovGateway {
  const failureMode = options?.failureMode ?? "none";

  return {
    name: "mock-gov-gateway",
    isMock: true,

    async submitApplication(
      input: SubmitApplicationInput,
    ): Promise<SubmitApplicationResult> {
      if (failureMode === "unavailable") {
        log.warn("gov.submit.portal_unavailable", {
          schemeCode: input.schemeCode,
          simulated: true,
        });
        return {
          ok: false,
          reason: "PORTAL_UNAVAILABLE",
          message:
            "The government portal did not respond. (Simulated failure: the application has NOT been lodged.)",
        };
      }

      // Keyed on the caller's idempotency key (one per entitlement), NOT on the
      // last four digits of Aadhaar. Keying on those four digits meant two
      // different citizens who happened to share them could not both apply:
      // the second was told an application already existed.
      const applicationRef = makeRef("GOVAPP", [
        input.schemeCode,
        input.idempotencyKey,
      ]);

      // Idempotency: the same key returning the same application is what
      // stops a retried request lodging a second claim.
      const existingByRef = await prisma.govApplication.findUnique({
        where: { applicationRef },
      });

      if (existingByRef) {
        // Same idempotency key, so this is a retry of a submission that already
        // landed - a double-click, or a timeout after the portal had in fact
        // accepted it. Return the original as a success. Reporting it as a
        // failure would flip a lodged application to SUBMISSION_FAILED.
        log.info("gov.submit.deduplicated", {
          schemeCode: input.schemeCode,
          applicationRef,
          simulated: true,
        });
        return {
          ok: true,
          applicationRef,
          status: existingByRef.status,
          receivedOn: existingByRef.receivedOn,
          deduplicated: true,
        };
      }

      const fieldErrors = validateFields(input);
      if (fieldErrors.length > 0) {
        return {
          ok: false,
          reason: "VALIDATION_REJECTED",
          message: "The portal rejected the application form.",
          fieldErrors,
        };
      }

      const status: GovApplicationStatus = "RECEIVED";

      await prisma.govApplication.create({
        data: {
          applicationRef,
          schemeCode: input.schemeCode,
          aadhaarLast4: input.aadhaarLast4,
          status,
          receivedOn: input.submittedAt,
        },
      });

      await prisma.govStatusEvent.create({
        data: {
          applicationRef,
          schemeCode: input.schemeCode,
          status,
          note: `Application received through ${input.documents.length} attached document(s) and ${input.declarations.length} declaration(s).`,
          occurredOn: input.submittedAt,
        },
      });

      log.info("gov.submit.accepted", {
        schemeCode: input.schemeCode,
        applicationRef,
        simulated: true,
      });

      return {
        ok: true,
        applicationRef,
        status,
        receivedOn: input.submittedAt,
        deduplicated: false,
      };
    },

    async getApplicationStatus(applicationRef) {
      return toStatusResult(applicationRef);
    },

    async listDisbursements(ref: {
      applicationRef: string;
    }): Promise<GovDisbursementRecord[]> {
      const rows = await prisma.govDisbursement.findMany({
        where: { applicationRef: ref.applicationRef },
        orderBy: { releasedOn: "asc" },
      });

      return rows.map((row) => ({
        disbursementRef: row.disbursementRef,
        applicationRef: row.applicationRef,
        schemeCode: row.schemeCode,
        periodLabel: row.periodLabel,
        amountPaise: row.amountPaise,
        releasedOn: row.releasedOn,
        channel: row.channel,
        bankAccountLast4: row.bankAccountLast4,
        status: row.status,
        failureReason: row.failureReason,
      }));
    },

    async correctInformation(
      input: CorrectInformationInput,
    ): Promise<GovOperationResult> {
      if (failureMode === "unavailable") {
        return {
          ok: false,
          reason: "PORTAL_UNAVAILABLE",
          message: "The portal did not respond. (Simulated failure.)",
        };
      }

      const application = await prisma.govApplication.findUnique({
        where: { applicationRef: input.applicationRef },
      });
      if (!application) {
        return {
          ok: false,
          reason: "NOT_FOUND",
          message: "No such application at the portal.",
        };
      }

      const reference = makeRef("GOVCOR", [input.idempotencyKey]);
      const acceptedOn = input.requestedAt;

      await prisma.govStatusEvent.create({
        data: {
          applicationRef: input.applicationRef,
          schemeCode: input.schemeCode,
          status: "CORRECTION_ACCEPTED",
          note: `Correction accepted for ${Object.keys(input.corrections).join(", ")}: ${input.reason}`,
          occurredOn: acceptedOn,
        },
      });

      return {
        ok: true,
        reference,
        acceptedOn,
        note: "The correction was accepted for processing. (Simulated.)",
      };
    },

    async submitDocument(input: SubmitDocumentInput): Promise<GovOperationResult> {
      if (failureMode === "unavailable") {
        return {
          ok: false,
          reason: "PORTAL_UNAVAILABLE",
          message: "The portal did not respond. (Simulated failure.)",
        };
      }

      const application = await prisma.govApplication.findUnique({
        where: { applicationRef: input.applicationRef },
      });
      if (!application) {
        return {
          ok: false,
          reason: "NOT_FOUND",
          message: "No such application at the portal.",
        };
      }

      // Supplying the document the portal was waiting for clears the hold and
      // returns the application to review.
      const clearsHold =
        application.status === "PENDING_DOCUMENT" ||
        application.status === "RETURNED";

      await prisma.govApplication.update({
        where: { applicationRef: input.applicationRef },
        data: clearsHold
          ? { status: "UNDER_REVIEW", pendingDocument: null }
          : {},
      });

      await prisma.govStatusEvent.create({
        data: {
          applicationRef: input.applicationRef,
          schemeCode: input.schemeCode,
          status: clearsHold ? "UNDER_REVIEW" : application.status,
          // The hash records that a document was received without retaining it.
          note: `Document ${input.documentKind} received (sha256 ${input.documentSha256.slice(0, 12)}...).`,
          occurredOn: input.requestedAt,
        },
      });

      return {
        ok: true,
        reference: makeRef("GOVDOC", [input.idempotencyKey]),
        acceptedOn: input.requestedAt,
        note: clearsHold
          ? "The document was accepted and the application returned to review. (Simulated.)"
          : "The document was accepted. (Simulated.)",
      };
    },
  };
}

let cached: GovGateway | null = null;

/**
 * The process-wide gateway.
 *
 * There is only a mock implementation. When a real integration exists it is
 * selected here, and nothing upstream changes.
 */
export function govGateway(): GovGateway {
  cached ??= createMockGovGateway();
  return cached;
}

/** Replace the gateway. Used by tests and by the demo console. */
export function setGovGateway(gateway: GovGateway | null): void {
  cached = gateway;
}
